retry later when sync to clusters failed
kubernetes-sigs/kubefed pull request #1250
Opened 2020-07-14 02:44 UTC by ansinlee

**What this PR does / why we need it**:
when sync to cluster failed, we need wait for the next federated resource changed for the next reconcile, it is indeterminacy, so we need retry later 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

2020-07-14 03:45 UTC, RainbowMango commented
Hi @ansinlee just a remember, your commit `cb92531` may need be squashed.

2020-07-14 16:35 UTC, hectorj2f commented
@ansinlee please, squash the commit into a single one, thanks

2020-07-16 10:45 UTC, hectorj2f commented
ideally it'd prefer to have more details about this issue, and a test to understand the problem and solution.

2020-09-18 21:20 UTC, makkes requested changes

2020-09-18 21:20 UTC, makkes commented on pkg/controller/sync/controller.go
> +	}
It is preferable to make use of the `ok` variable right after it has been assigned, i.e. on line 370. This way it's much easier to follow the reasoning of why it is assigned in the first place.

2020-10-28 16:20 UTC, makkes commented
@ansinlee are you still working on this? Asking because there has not been activity on it for quite some time now. 🙂

2021-03-27 18:38 UTC, closed without merging