optimize chart readme
kubernetes-sigs/kubefed pull request #1328
Opened 2020-12-15 03:21 UTC by huiwq1990

**What this PR does / why we need it**:

1) As upgrade CustomResourceDefinition in #1296 ,  kubefed only support 1.16+
2) controllermanager docker image split into controller image and webhook image 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

2020-12-15 11:44 UTC, makkes approved these changes

2020-12-15 11:44 UTC, makkes commented
/lgtm

Thanks a lot, @huiwq1990.

2020-12-15 12:50 UTC, irfanurrehman requested changes
Thanks @huiwq1990 
I might be missing something, but it appears like there are duplicates. Please check and let me know.

2020-12-15 12:50 UTC, irfanurrehman commented on charts/kubefed/README.md
> +| controllermanager.controller.replicaCount      | Number of replicas for KubeFed controller manager.
This seems like a repeat of line 107?

2020-12-15 12:50 UTC, irfanurrehman commented on charts/kubefed/README.md
> +| controllermanager.controller.imagePullPolicy   | Image pull policy.
Did you mean `controllermanager.webhook.imagePullPolicy`?

2020-12-15 16:20 UTC, huiwq1990 commented
@irfanurrehman I have recheck my pr, and fix them.

2020-12-15 16:21 UTC, huiwq1990 commented
yes, my mistake.

2020-12-15 16:21 UTC, makkes commented
We should put all options in (alphabetic?) order but that can be done in a subsequent PR.

/lgtm

2020-12-15 16:22 UTC, huiwq1990 commented on charts/kubefed/README.md
> +| controllermanager.controller.replicaCount      | Number of replicas for KubeFed controller manager.
yes, i have fix them.

2020-12-15 16:32 UTC, huiwq1990 commented
I prefer organize them by kubefed’s module(webhook,controller).  User know how to config them at first glance.

2020-12-16 07:35 UTC, irfanurrehman commented
Thanks @huiwq1990 
/approve

2020-12-16 07:36 UTC, irfanurrehman approved these changes

2020-12-16 07:36 UTC, merged