support retain custom fields for federate resource
kubernetes-sigs/kubefed pull request #1381
Opened 2021-03-18 03:44 UTC by shiyan2016

**What this PR does / why we need it**:
Define a list of fields for resource that if they're updated on some cluster won't trigger federation controller to sync and overwrite them.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes-sigs/kubefed/issues/1370

**Special notes for your reviewer**:

2021-03-19 06:11 UTC, shiyan2016 commented
@gyliu513 @makkes Can you help me to review this PR? Thanks.

2021-03-19 08:25 UTC, hectorj2f requested changes
@shiyan2016 Thanks for opening this PR and proposing changes to kubefed. 

However I am missing the context here. I'd like to see a KEP document where you explain the motivation/examples/user stories to add this feature. Also I think we need this kind of behaviors to be enabled by a Feature Gate that is how we added some other changes here that affect to the reconciliation loops of the kubefed core.
Generally, we should initially discuss it in the KEP and approve it before going and merging into the code.
Another detail we might also want to see, it could be how it affects to the current performance of kubefed.

In particular for this PR, we are missing e2e tests here, so we cannot evaluate how does work for common resources.

2021-03-19 09:27 UTC, shiyan2016 commented
@hectorj2f There are some discussions for this PR: https://github.com/kubernetes-sigs/kubefed/issues/1370. And I will add the KEP doc and improve the code with feature gate and add e2e tests. Thanks.

2021-03-24 10:06 UTC, hectorj2f commented
Thanks @shiyan2016. I missed your last comment.

2021-06-01 03:22 UTC, closed without merging