fix: updating scripts to be used on quickstart
kubernetes-sigs/kubefed pull request #1495
Opened 2022-02-23 19:40 UTC by msdolbey

on macOS

**What this PR does / why we need it**:
This should resolve this issue for macOS users for this:
https://github.com/kubernetes-sigs/kubefed/issues/1494

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1494
[issue 1494](https://github.com/kubernetes-sigs/kubefed/issues/1494)

**Special notes for your reviewer**:
I've tested this on my machine and it works for me, and I've started from scratch a few times and have encountered the same issue. So, I don't think it's isolated to me, but perhaps there is a docker version/macOS version thing that could be hanging this up. I do know this fixes the issues I encountered.

2022-02-24 03:26 UTC, msdolbey commented
Hmm - saw some tests failed - looks like some dependencies might have been bumped, and the versions that were being looked for previously may now be getting the most recent release?
https://github.com/kubernetes-sigs/kubefed/runs/5313295967?check_suite_focus=true#step:4:122
If it's looking for this?
https://github.com/msdolbey/kubefed/blob/msdolbey/issues-with-quickstart-macOS/Makefile#L156
but the latest release is:
https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.8.0
Could that be it?

2022-02-24 08:18 UTC, irfanurrehman commented
@msdolbey I will take a look at this. You will have to give me few days though... :-)

2022-02-24 08:27 UTC, makkes requested changes

2022-02-24 16:47 UTC, msdolbey commented on scripts/fix-joined-kind-clusters.sh
> +    IP_ADDR="$(docker inspect -f "${INSPECT_PATH}" "kind-control-plane")"
I guess just from the quick start instructions - only one is set up per the instructions - but, all things docker tend to be a bit out of my depth, tbh. I just know that I was hitting an error before, and this sorted it out on my side.

2022-02-25 08:25 UTC, makkes commented on scripts/fix-joined-kind-clusters.sh
> +    IP_ADDR="$(docker inspect -f "${INSPECT_PATH}" "kind-control-plane")"
Fair enough. The problem is, though, that this script isn't only used in the quick start but also referenced [here](https://github.com/kubernetes-sigs/kubefed/blob/ae42003b1fdfab1cd3bffff5bef25de429783fa0/docs/cluster-registration.md#joining-kind-clusters-on-macos) for basically fixing any joined cluster so it needs to be more generic.

2022-02-25 23:03 UTC, msdolbey commented
Good point - I'll try to get to all these concerns this weekend. Thanks!

2022-03-22 06:03 UTC, irfanurrehman commented
@msdolbey I fixed some test flakes last weekend. Can you please rebase your changes on latest. Also did you get time to address @makkes comments.

2022-06-20 13:16 UTC, makkes commented
@msdolbey did you find the time to address the comments, yet? I'd be happy to help get this over the line

2022-08-19 14:39 UTC, closed without merging